package loop.model.simulator;

import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;

import loop.model.UserConfiguration;
import loop.model.simulationengine.IterationResult;
import loop.model.simulator.exception.SimulationEngineException;

/**
 * A SimulationResult object contains information about a started simulation,
 * such as its configuration, execution status, id and, if available, the
 * results of the iterations. It is generated by a Simulator when a simulation
 * is started. The class does not distinguish between multiconfigurations and
 * non-multiconfigurations, so it generally assumes that several elementary
 * configurations underlie.
 * 
 * @author Christian Schorr
 *
 */
public class SimulationResult {

	private UserConfiguration configuration;
	private int id;

	private List<List<IterationResult>> iterationResults;
	private List<SimulationEngineException> exceptions;
		
	private List<BiConsumer<SimulationResult, IterationResult>> resultHandlers;
	private List<BiConsumer<SimulationResult, SimulationEngineException>> exceptionHandlers;

	/**
	 * Creates a new simulation result to a simulation with given configuration and
	 * id.
	 * 
	 * @param config the configuration of the simulation
	 * @param id     the id of the simulation
	 */
	public SimulationResult(UserConfiguration config, int id) {
		configuration = config;
		this.id = id;
		iterationResults = new ArrayList<List<IterationResult>>();
		exceptions = new ArrayList<SimulationEngineException>();
		
		resultHandlers = new ArrayList<BiConsumer<SimulationResult, IterationResult>>();
		exceptionHandlers = new ArrayList<BiConsumer<SimulationResult, SimulationEngineException>>();
	}

	/**
	 * adds an {@link IterationResult} to the i-th elementary configuration and
	 * triggers all registered actions.
	 * 
	 * @param result the iteration result that shall be added
	 * @param i      the elementary configuration to which the given result shall be
	 *               added
	 */
	protected void addIterationResult(IterationResult result, int i) {
		int listsToAdd = (i + 1) - iterationResults.size();
		for (int j = 0; j < listsToAdd; i++) {
			iterationResults.add(new ArrayList<IterationResult>());
		}		
		iterationResults.get(i).add(result);
		
		// notify listeners
		for (BiConsumer<SimulationResult, IterationResult> handler : resultHandlers) {
			handler.accept(this, result);
		}
	}

	/**
	 * Adds a {@link SimulationEngineException} to this Simulaton and triggers all
	 * registered exception handlers
	 * 
	 * @param ex the exception that shall be added
	 */
	protected void addSimulationEngineException(SimulationEngineException ex) {
		exceptions.add(ex);
		
		// notify listeners
		for (BiConsumer<SimulationResult, SimulationEngineException> handler : exceptionHandlers) {
			handler.accept(this, ex);
		}
	}

	/**
	 * Registers an action that will be executed every time an iteration of this
	 * simulation is finished. The IterationResult of the iteration as well as this
	 * instance will be passed as an argument to the action.
	 * 
	 * @param action the action that shall be executed whenever an iteration
	 *               finishes
	 */
	public void registerIterationFinished(BiConsumer<SimulationResult, IterationResult> action) {
		resultHandlers.add(action);
	}

	/**
	 * Registers a handler that will be executed every time an exception
	 * corresponding to this simulation occurs.
	 * 
	 * @param handler the handler that shall be executed whenever an exception
	 *                occurs
	 */
	public void registerExceptionHandler(BiConsumer<SimulationResult, SimulationEngineException> handler) {
		exceptionHandlers.add(handler);
	}

	/**
	 * Returns a list of all yet available results of iterations with the i-th
	 * elementary configuration.
	 * 
	 * @param i the elementary configuration whose finished iterations shall be
	 *          returned
	 * @return a list of all yet available results of iterations with the i -th
	 *         elementary configuration
	 */
	public List<IterationResult> getIterationResults(int i) {
		if (i < 0 || i > iterationResults.size() - 1) return null;
		return iterationResults.get(i);
	}

	/**
	 * Returns the {@link UserConfiguration} of this simulation.
	 * 
	 * @return the {@link UserConfiguration} of this simulation
	 */
	public UserConfiguration getUserConfiguration() {
		return configuration;
	}

	/**
	 * Returns the amount of elementary configurations of this simulation (1 if this
	 * is not a multiconfiguration).
	 * 
	 * @return the amount of elementary configurations of this simulation
	 */
	public int getConfigurationCount() {
		return iterationResults.size();
	}

	/**
	 * Returns the id of this simulation.
	 * 
	 * @return the id of this simulation
	 */
	public int getId() {
		return id;
	}
}
